// src/components/Footer.tsx
import { AtSign, Github, Linkedin, Twitter } from "lucide-react";

export default function Footer() {
  return (
    <footer className="w-full bg-gradient-to-b from-neutral-800 via-transparent to-transparent border-t border-neutral-700 pt-4 pb-12 mt-24 flex justify-center items-center">
      <div className="w-full px-4 flex justify-between items-center">
        <p className="text-neutral-200 text-sm w-full">
          Copyright © 2023 Irvan Malik Azantha.
          <span className="block">
            Built with{" "}
            <a
              href="https://astro.build/"
              className="text-red-400 hover:text-neutral-200 underline transition"
            >
              Astro
            </a>{" "}
            and{" "}
            <a
              href="https://tailwindcss.com"
              className="text-red-400 hover:text-neutral-200 underline transition"
            >
              Tailwind
            </a>
            , deployed on{" "}
            <a
              href="https://pages.cloudflare.com"
              className="text-red-400 hover:text-neutral-200 underline transition"
            >
              Cloudflare Pages
            </a>
            .
          </span>
        </p>
      </div>
      <div className="flex px-4 gap-1 items-center">
        <a
          href="https://linkedin.com/in/irvanmalik48"
          className="nav-item rounded-full"
          aria-label="LinkedIn Profile"
        >
          <Linkedin size={18} />
        </a>
        <a
          href="https://twitter.com/irvanmalik48"
          className="nav-item rounded-full"
          aria-label="Twitter Profile"
        >
          <Twitter size={18} />
        </a>
        <a
          href="https://github.com/irvanmalik48"
          className="nav-item rounded-full"
          aria-label="Github Profile"
        >
          <Github size={18} />
        </a>
        <a
          href="mailto:irvanmalik48@gmail.com"
          className="nav-item rounded-full"
          aria-label="Email Handle"
        >
          <AtSign size={18} />
        </a>
      </div>
    </footer>
  );
}

// apps/realm/src/components/footer/footer.tsx
import { component$ } from "@builder.io/qwik";
import { FooterTop } from "../footer-top/footer-top";
import { twMerge } from "tailwind-merge";

export default component$(() => {
  return (
    <>
      <FooterTop class="w-full" />
      <footer
        class={twMerge(
          "w-full px-5 pt-2 pb-4 bg-neutral-900/20",
          "text-neutral-100"
        )}
      >
        <div class="mx-auto max-w-4xl flex flex-col gap-1 items-center">
          <p
            class={twMerge(
              "text-center text-sm rounded-full px-5 py-1",
              "leading-sm mb-2 bg-neutral-900 font-heading"
            )}
          >
            <span class="text-neutral-300">© 2023 Irvan Malik Azantha</span>
          </p>
          <p class="text-center text-sm">
            <span class="text-neutral-300">
              Made with
              <a
                href="https://qwik.builder.io"
                class="mx-1 text-neutral-300 hover:text-neutral-100"
              >
                Qwik
              </a>
              and
              <a
                href="https://tailwindcss.com"
                class="ml-1 text-neutral-300 hover:text-neutral-100"
              >
                Tailwind
              </a>
            </span>
            <span class="mx-4 text-neutral-300">|</span>
            <span class="text-neutral-300">Hosted on</span>
            <a
              href="https://cloudflare.com"
              class="mx-1 text-neutral-300 hover:text-neutral-100"
            >
              Cloudflare Pages
            </a>
            <span class="mx-4 text-neutral-300">|</span>
            <span class="text-neutral-300">Powered by coffee and anime</span>
          </p>
        </div>
      </footer>
    </>
  );
});
